services:
  - type: web
    name: curenet-backend
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable fonts-freefont-ttf
      mkdir -p /opt/render/.cache/puppeteer/chrome
      ln -s /usr/bin/google-chrome /opt/render/.cache/puppeteer/chrome/chrome
      npm install
      chmod -R o+rx /opt/render/.cache/puppeteer/chrome
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: CHROME_PATH
        value: /opt/render/.cache/puppeteer/chrome/chrome
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: chrome-cache
      mountPath: /opt/render/.cache
      sizeGB: 1
