services:
  - type: web
    name: curenet-backend
    env: node
    buildCommand: npm run build
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chromium/chrome-linux64/chrome
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
